### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by alvlasov** [JongWasTaken/moretools#13]
Hi!

I made a russian translation for this mod. Could you include it in the repository?
[moretools-1.7.2+1.21-Russian.zip](https://github.com/user-attachments/files/17296753/moretools-1.7.2%2B1.21-Russian.zip)

**Comment by JongWasTaken** [comment]
Hello,  
thank you for your contribution! The translation will be available in version 1.7.3, which I will publish later today.  
Have a great day!
