### ISSUE TITLE
Excavator not pathing blocks

### ISSUE THREAD

**Issue by ikon106** [JongWasTaken/moretools#14]
At least the diamond excavator doesn't flatten/make path blocks correctly. It would be nice if it did in a 3x3 area, but at least the block one clicks on.

**Comment by JongWasTaken** [comment]
Hello,
thank you for opening an issue for this.  
To be frank, I completely forgot about paths. Weirdly enough nobody opened an issue for it until now.  
  
In any case, I just pushed version 1.7.4 which adds right-clicking for both excavators and saws.  
  
Thank you, and have a great day!

**Comment by ikon106** [comment]
Weird that no one else has mentioned it, but I'm glad you fixed it. Thanks for that and for a great mod!
