### ISSUE TITLE
[Feature Request] Nether- and Warped Wart blocks also get mined with saw

### ISSUE THREAD

**Issue by ikon106** [JongWasTaken/moretools#15]
It'd be very convenient if chopping a nether tree would also drop the "leaves" since they don't decay naturally. But this might be unbalanced since it's normally broken with a hoe and not an axe.

**Comment by JongWasTaken** [comment]
Hello, thank you for opening an issue.

Considering that saws also break leaves quickly, I will consider adding this in a future release.  
  
Until then, you can achieve this using a simple datapack:  
[moretools-nether-trees.zip](https://github.com/user-attachments/files/17750750/moretools-nether-trees.zip)  
  
This datapack adds the identifiers for the nether wart block and the warped wart block to the `saw_mineable.json` tag file, making them mineable.  

Have a great day!

**Comment by ikon106** [comment]
Perfect, thank you!
