### ISSUE TITLE
Fabric rejects version 1.3.0 with versions under 1.20.6

### ISSUE THREAD

**Issue by Bratorsortnal** [JongWasTaken/moretools#3]
It's said that version 1.3.0 is for 1.20.1, 4 and 6. Fabric only lets you launch the game on 1.20.6 though.

**Comment by JongWasTaken** [comment]
Just checking: you _did_ download the correct file, right?
![image](https://github.com/JongWasTaken/moretools/assets/30602169/9605dc17-160b-4eb0-96aa-7e5d8c49f74c)
