### ISSUE TITLE
Java version Incompatibility with 1.20.4 version

### ISSUE THREAD

**Issue by osamadnver** [JongWasTaken/moretools#6]
![image](https://github.com/JongWasTaken/moretools/assets/139006210/388d96ea-e5cf-433f-8a0c-81898844882c)
![image](https://github.com/JongWasTaken/moretools/assets/139006210/2d92381f-1c3b-4654-b159-a95212062cc9)

**Comment by JongWasTaken** [comment]
Whoops, looks like I forgot to update that when I backported some changes to 1.20.4 and 1.20.1.  
I just published version 1.4.3 for 1.20.4 and 1.20.1 which should fix this issue (might take a few hours on CurseForge, Modrinth already has it).  
  
Thank you for reporting this issue!
