### ISSUE TITLE
Item Durability

### ISSUE THREAD

**Issue by ProSabre** [JongWasTaken/moretools#7]
Hi,

I noticed the other day when playing with this mod that the durability numbers don't appear to be comparable to the cost of the items consumed in the crafting recipe. When the hammer is crafted, it has the same durability as a single pickaxe of that type (i.e. Wood, Stone, Iron, etc).
I did some testing in a single player world and confirmed that each level of the hammer has the same durability as its pickaxe counterpart. 

For these tools to be remotely viable, I would have expected the hammers to have the durability of all three of the pickaxes used in the crafting recipe. 
I.e.:
Wood:
- Pickaxe - 59
- Hammer - 177
Stone:
- Pickaxe - 131
- Hammer - 393
Iron:
- Pickaxe - 250
- Hammer - 750
Gold:
- Pickaxe - 32
- Hammer - 96
Diamond:
- Pickaxe - 1561
- Hammer - 4683
Netherite:
- Pickaxe - 2031
- Hammer - 6093

I did look to see if I could find a config to rectify this but I couldn't seem to find one. I'm new to using polymer mods so this might just be how they work.

Sorry about the rambling but I hope this can be fixed as this mod is really great to use!
Kind Regards :D

**Comment by JongWasTaken** [comment]
Hey,  
to be honest, this is just a simple oversight, and I fully agree.  
I use these tools with mending or unbreaking most of the time, so I kinda forgot about this (and nobody brought it up until now!).  
  
I looked into implementing it just now and noticed a slight problem (or rather, an inconsistency that annoys me):  
  
The durability tooltip is fully client-side.  
Essentially I set the durability to be the base durability times 3, but the tooltip did not update. Only when breaking blocks did I finally notice: the new durability itself was applied correctly, but the tooltip was still showing vanilla values.  
  
My band-aid solution to this is an additional tooltip, which shows the "true" durability:  
![image](https://github.com/JongWasTaken/moretools/assets/30602169/ecd31177-f51d-465a-ae3c-c60fb99ade3a)
  
While I am not really a fan of this, I cannot think of a better way of doing this, so I will probably keep this.  
  
So as it stands I will probably add this in the next release, though I am not sure when I will have the time to release that, as I won't be at home for the next few days.  
  
Anyways, thank you for reporting this and have a nice day!

**Comment by ProSabre** [comment]
Hey!

Thank you for the prompt reply!

I see the problem and I can definitely imagine the annoyance.
The issue that I am having thought is that the hammer is breaking at 1/3 of its intended durability. I’m not sure if this is the client being confused and sending the server a destroy item command or what.

Take your time! There are ways of working around this currently. Hopefully you can get it fully sorted in the next update.

Again, thank you for such a prompt reply!

Hope you have an amazing rest of your week.

**Comment by JongWasTaken** [comment]
Hello again!  
I kinda couldn't help myself and finished up the update...  
  
And good news: it looks like Mojang actually changed the way the durability tooltip is rendered on 1.20.5 and onwards, which means there is no need for an additional tooltip on these versions.  
  
I just pushed the update to Modrinth and CurseForge, though files on CurseForge need to go through an approval process that might take up to a few hours.  
  
With this I will be closing this issue. If you notice any other issues or problems feel free to open another one.  
  
Thanks you for using my mod!
