### ISSUE TITLE
Problem with crafting

### ISSUE THREAD

**Issue by MolBriwat** [JongWasTaken/moretools#8]
Hello Jong I hope you're doing great, I just wanna submit an issue that is a bit annoying. The tools aren't working if you craft them in survival, it works just like a normal pickaxe, you have to get them in creative mode then change to survival mode for it to work, and we're using this mod in a server where we don't have permission to change gamemodes, so yeah can you fix this problem as quick as possible, Thank you for your work!

**Comment by JongWasTaken** [comment]
Hey there, and thank you for opening an issue.  
    
Could you please tell which Minecraft version you are using?  
Also, I assume you are using version 1.5.0 of MoreTools?

**Comment by Elyas2024** [comment]
its possible to get them in creative using the polymer creative tabs, to get there, just type the command: /polymer and look for the creative suggestion by clicking tab

**Comment by JongWasTaken** [comment]
It has been 2 weeks without a reply from the original poster.  
I was not able to reproduce this issue in my testing, so this issue will be closed.  
  
Should this issue still exist, please comment here or open a new issue and I will take another look.
